/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: agent_servers.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "agent_servers.pb-c.h"
void   agent_server_node__init
                     (AgentServerNode         *message)
{
  static AgentServerNode init_value = AGENT_SERVER_NODE__INIT;
  *message = init_value;
}
size_t agent_server_node__get_packed_size
                     (const AgentServerNode *message)
{
  assert(message->base.descriptor == &agent_server_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t agent_server_node__pack
                     (const AgentServerNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &agent_server_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t agent_server_node__pack_to_buffer
                     (const AgentServerNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &agent_server_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AgentServerNode *
       agent_server_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AgentServerNode *)
     protobuf_c_message_unpack (&agent_server_node__descriptor,
                                allocator, len, data);
}
void   agent_server_node__free_unpacked
                     (AgentServerNode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &agent_server_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   agent_servers__init
                     (AgentServers         *message)
{
  static AgentServers init_value = AGENT_SERVERS__INIT;
  *message = init_value;
}
size_t agent_servers__get_packed_size
                     (const AgentServers *message)
{
  assert(message->base.descriptor == &agent_servers__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t agent_servers__pack
                     (const AgentServers *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &agent_servers__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t agent_servers__pack_to_buffer
                     (const AgentServers *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &agent_servers__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AgentServers *
       agent_servers__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AgentServers *)
     protobuf_c_message_unpack (&agent_servers__descriptor,
                                allocator, len, data);
}
void   agent_servers__free_unpacked
                     (AgentServers *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &agent_servers__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const protobuf_c_boolean agent_server_node__need_login__default_value = 0;
static const ProtobufCFieldDescriptor agent_server_node__field_descriptors[6] =
{
  {
    "server_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AgentServerNode, server_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_pipe",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AgentServerNode, is_pipe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AgentServerNode, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AgentServerNode, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_id",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AgentServerNode, server_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "need_login",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AgentServerNode, need_login),
    NULL,
    &agent_server_node__need_login__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned agent_server_node__field_indices_by_name[] = {
  2,   /* field[2] = address */
  1,   /* field[1] = is_pipe */
  5,   /* field[5] = need_login */
  3,   /* field[3] = port */
  4,   /* field[4] = server_id */
  0,   /* field[0] = server_name */
};
static const ProtobufCIntRange agent_server_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor agent_server_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "agent_server_node",
  "AgentServerNode",
  "AgentServerNode",
  "",
  sizeof(AgentServerNode),
  6,
  agent_server_node__field_descriptors,
  agent_server_node__field_indices_by_name,
  1,  agent_server_node__number_ranges,
  (ProtobufCMessageInit) agent_server_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor agent_servers__field_descriptors[1] =
{
  {
    "servers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AgentServers, n_servers),
    offsetof(AgentServers, servers),
    &agent_server_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned agent_servers__field_indices_by_name[] = {
  0,   /* field[0] = servers */
};
static const ProtobufCIntRange agent_servers__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor agent_servers__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "agent_servers",
  "AgentServers",
  "AgentServers",
  "",
  sizeof(AgentServers),
  1,
  agent_servers__field_descriptors,
  agent_servers__field_indices_by_name,
  1,  agent_servers__number_ranges,
  (ProtobufCMessageInit) agent_servers__init,
  NULL,NULL,NULL    /* reserved[123] */
};
