/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: database_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "database_config.pb-c.h"
void   database_node__init
                     (DatabaseNode         *message)
{
  static DatabaseNode init_value = DATABASE_NODE__INIT;
  *message = init_value;
}
size_t database_node__get_packed_size
                     (const DatabaseNode *message)
{
  assert(message->base.descriptor == &database_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t database_node__pack
                     (const DatabaseNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &database_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t database_node__pack_to_buffer
                     (const DatabaseNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &database_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DatabaseNode *
       database_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DatabaseNode *)
     protobuf_c_message_unpack (&database_node__descriptor,
                                allocator, len, data);
}
void   database_node__free_unpacked
                     (DatabaseNode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &database_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   database_config__init
                     (DatabaseConfig         *message)
{
  static DatabaseConfig init_value = DATABASE_CONFIG__INIT;
  *message = init_value;
}
size_t database_config__get_packed_size
                     (const DatabaseConfig *message)
{
  assert(message->base.descriptor == &database_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t database_config__pack
                     (const DatabaseConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &database_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t database_config__pack_to_buffer
                     (const DatabaseConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &database_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DatabaseConfig *
       database_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DatabaseConfig *)
     protobuf_c_message_unpack (&database_config__descriptor,
                                allocator, len, data);
}
void   database_config__free_unpacked
                     (DatabaseConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &database_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor database_node__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DatabaseNode, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DatabaseNode, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DatabaseNode, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DatabaseNode, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DatabaseNode, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dbname",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DatabaseNode, dbname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned database_node__field_indices_by_name[] = {
  1,   /* field[1] = address */
  5,   /* field[5] = dbname */
  0,   /* field[0] = name */
  4,   /* field[4] = password */
  2,   /* field[2] = port */
  3,   /* field[3] = username */
};
static const ProtobufCIntRange database_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor database_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "database_node",
  "DatabaseNode",
  "DatabaseNode",
  "",
  sizeof(DatabaseNode),
  6,
  database_node__field_descriptors,
  database_node__field_indices_by_name,
  1,  database_node__number_ranges,
  (ProtobufCMessageInit) database_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor database_config__field_descriptors[1] =
{
  {
    "databases",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DatabaseConfig, n_databases),
    offsetof(DatabaseConfig, databases),
    &database_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned database_config__field_indices_by_name[] = {
  0,   /* field[0] = databases */
};
static const ProtobufCIntRange database_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor database_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "database_config",
  "DatabaseConfig",
  "DatabaseConfig",
  "",
  sizeof(DatabaseConfig),
  1,
  database_config__field_descriptors,
  database_config__field_indices_by_name,
  1,  database_config__number_ranges,
  (ProtobufCMessageInit) database_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
