/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: db_query.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "db_query.pb-c.h"
void   db_query_param__init
                     (DbQueryParam         *message)
{
  static DbQueryParam init_value = DB_QUERY_PARAM__INIT;
  *message = init_value;
}
size_t db_query_param__get_packed_size
                     (const DbQueryParam *message)
{
  assert(message->base.descriptor == &db_query_param__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_query_param__pack
                     (const DbQueryParam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_query_param__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_query_param__pack_to_buffer
                     (const DbQueryParam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_query_param__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbQueryParam *
       db_query_param__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbQueryParam *)
     protobuf_c_message_unpack (&db_query_param__descriptor,
                                allocator, len, data);
}
void   db_query_param__free_unpacked
                     (DbQueryParam *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_query_param__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_query__init
                     (DbQuery         *message)
{
  static DbQuery init_value = DB_QUERY__INIT;
  *message = init_value;
}
size_t db_query__get_packed_size
                     (const DbQuery *message)
{
  assert(message->base.descriptor == &db_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_query__pack
                     (const DbQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_query__pack_to_buffer
                     (const DbQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbQuery *
       db_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbQuery *)
     protobuf_c_message_unpack (&db_query__descriptor,
                                allocator, len, data);
}
void   db_query__free_unpacked
                     (DbQuery *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_field__init
                     (DbField         *message)
{
  static DbField init_value = DB_FIELD__INIT;
  *message = init_value;
}
size_t db_field__get_packed_size
                     (const DbField *message)
{
  assert(message->base.descriptor == &db_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_field__pack
                     (const DbField *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_field__pack_to_buffer
                     (const DbField *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbField *
       db_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbField *)
     protobuf_c_message_unpack (&db_field__descriptor,
                                allocator, len, data);
}
void   db_field__free_unpacked
                     (DbField *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_fields__init
                     (DbFields         *message)
{
  static DbFields init_value = DB_FIELDS__INIT;
  *message = init_value;
}
size_t db_fields__get_packed_size
                     (const DbFields *message)
{
  assert(message->base.descriptor == &db_fields__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_fields__pack
                     (const DbFields *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_fields__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_fields__pack_to_buffer
                     (const DbFields *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_fields__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbFields *
       db_fields__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbFields *)
     protobuf_c_message_unpack (&db_fields__descriptor,
                                allocator, len, data);
}
void   db_fields__free_unpacked
                     (DbFields *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_fields__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_row_value__init
                     (DbRowValue         *message)
{
  static DbRowValue init_value = DB_ROW_VALUE__INIT;
  *message = init_value;
}
size_t db_row_value__get_packed_size
                     (const DbRowValue *message)
{
  assert(message->base.descriptor == &db_row_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_row_value__pack
                     (const DbRowValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_row_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_row_value__pack_to_buffer
                     (const DbRowValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_row_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbRowValue *
       db_row_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbRowValue *)
     protobuf_c_message_unpack (&db_row_value__descriptor,
                                allocator, len, data);
}
void   db_row_value__free_unpacked
                     (DbRowValue *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_row_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_row__init
                     (DbRow         *message)
{
  static DbRow init_value = DB_ROW__INIT;
  *message = init_value;
}
size_t db_row__get_packed_size
                     (const DbRow *message)
{
  assert(message->base.descriptor == &db_row__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_row__pack
                     (const DbRow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_row__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_row__pack_to_buffer
                     (const DbRow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_row__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbRow *
       db_row__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbRow *)
     protobuf_c_message_unpack (&db_row__descriptor,
                                allocator, len, data);
}
void   db_row__free_unpacked
                     (DbRow *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_row__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_rows__init
                     (DbRows         *message)
{
  static DbRows init_value = DB_ROWS__INIT;
  *message = init_value;
}
size_t db_rows__get_packed_size
                     (const DbRows *message)
{
  assert(message->base.descriptor == &db_rows__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_rows__pack
                     (const DbRows *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_rows__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_rows__pack_to_buffer
                     (const DbRows *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_rows__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbRows *
       db_rows__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbRows *)
     protobuf_c_message_unpack (&db_rows__descriptor,
                                allocator, len, data);
}
void   db_rows__free_unpacked
                     (DbRows *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_rows__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_error__init
                     (DbError         *message)
{
  static DbError init_value = DB_ERROR__INIT;
  *message = init_value;
}
size_t db_error__get_packed_size
                     (const DbError *message)
{
  assert(message->base.descriptor == &db_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_error__pack
                     (const DbError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_error__pack_to_buffer
                     (const DbError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbError *
       db_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbError *)
     protobuf_c_message_unpack (&db_error__descriptor,
                                allocator, len, data);
}
void   db_error__free_unpacked
                     (DbError *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_query_result__init
                     (DbQueryResult         *message)
{
  static DbQueryResult init_value = DB_QUERY_RESULT__INIT;
  *message = init_value;
}
size_t db_query_result__get_packed_size
                     (const DbQueryResult *message)
{
  assert(message->base.descriptor == &db_query_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_query_result__pack
                     (const DbQueryResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &db_query_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_query_result__pack_to_buffer
                     (const DbQueryResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &db_query_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbQueryResult *
       db_query_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbQueryResult *)
     protobuf_c_message_unpack (&db_query_result__descriptor,
                                allocator, len, data);
}
void   db_query_result__free_unpacked
                     (DbQueryResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &db_query_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor db_query_param__field_descriptors[2] =
{
  {
    "param_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbQueryParam, param_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbQueryParam, values),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_query_param__field_indices_by_name[] = {
  0,   /* field[0] = param_type */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange db_query_param__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor db_query_param__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_query_param",
  "DbQueryParam",
  "DbQueryParam",
  "",
  sizeof(DbQueryParam),
  2,
  db_query_param__field_descriptors,
  db_query_param__field_indices_by_name,
  1,  db_query_param__number_ranges,
  (ProtobufCMessageInit) db_query_param__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_query__field_descriptors[3] =
{
  {
    "conn",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbQuery, conn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbQuery, query),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "params",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbQuery, n_params),
    offsetof(DbQuery, params),
    &db_query_param__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_query__field_indices_by_name[] = {
  0,   /* field[0] = conn */
  2,   /* field[2] = params */
  1,   /* field[1] = query */
};
static const ProtobufCIntRange db_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor db_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_query",
  "DbQuery",
  "DbQuery",
  "",
  sizeof(DbQuery),
  3,
  db_query__field_descriptors,
  db_query__field_indices_by_name,
  1,  db_query__number_ranges,
  (ProtobufCMessageInit) db_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_field__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbField, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbField, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_field__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange db_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor db_field__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_field",
  "DbField",
  "DbField",
  "",
  sizeof(DbField),
  2,
  db_field__field_descriptors,
  db_field__field_indices_by_name,
  1,  db_field__number_ranges,
  (ProtobufCMessageInit) db_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_fields__field_descriptors[1] =
{
  {
    "fields",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbFields, n_fields),
    offsetof(DbFields, fields),
    &db_field__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_fields__field_indices_by_name[] = {
  0,   /* field[0] = fields */
};
static const ProtobufCIntRange db_fields__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor db_fields__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_fields",
  "DbFields",
  "DbFields",
  "",
  sizeof(DbFields),
  1,
  db_fields__field_descriptors,
  db_fields__field_indices_by_name,
  1,  db_fields__number_ranges,
  (ProtobufCMessageInit) db_fields__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean db_row_value__is_null__default_value = 0;
static const protobuf_c_boolean db_row_value__is_unsigned__default_value = 0;
static const ProtobufCFieldDescriptor db_row_value__field_descriptors[3] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DbRowValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_null",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbRowValue, is_null),
    NULL,
    &db_row_value__is_null__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_unsigned",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbRowValue, is_unsigned),
    NULL,
    &db_row_value__is_unsigned__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_row_value__field_indices_by_name[] = {
  1,   /* field[1] = is_null */
  2,   /* field[2] = is_unsigned */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange db_row_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor db_row_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_row_value",
  "DbRowValue",
  "DbRowValue",
  "",
  sizeof(DbRowValue),
  3,
  db_row_value__field_descriptors,
  db_row_value__field_indices_by_name,
  1,  db_row_value__number_ranges,
  (ProtobufCMessageInit) db_row_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_row__field_descriptors[1] =
{
  {
    "column",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbRow, n_column),
    offsetof(DbRow, column),
    &db_row_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_row__field_indices_by_name[] = {
  0,   /* field[0] = column */
};
static const ProtobufCIntRange db_row__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor db_row__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_row",
  "DbRow",
  "DbRow",
  "",
  sizeof(DbRow),
  1,
  db_row__field_descriptors,
  db_row__field_indices_by_name,
  1,  db_row__number_ranges,
  (ProtobufCMessageInit) db_row__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_rows__field_descriptors[1] =
{
  {
    "rows",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DbRows, n_rows),
    offsetof(DbRows, rows),
    &db_row__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_rows__field_indices_by_name[] = {
  0,   /* field[0] = rows */
};
static const ProtobufCIntRange db_rows__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor db_rows__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_rows",
  "DbRows",
  "DbRows",
  "",
  sizeof(DbRows),
  1,
  db_rows__field_descriptors,
  db_rows__field_indices_by_name,
  1,  db_rows__number_ranges,
  (ProtobufCMessageInit) db_rows__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_error__field_descriptors[3] =
{
  {
    "is_mysql_error",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbError, is_mysql_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DbError, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reason",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DbError, reason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_error__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  0,   /* field[0] = is_mysql_error */
  2,   /* field[2] = reason */
};
static const ProtobufCIntRange db_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor db_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_error",
  "DbError",
  "DbError",
  "",
  sizeof(DbError),
  3,
  db_error__field_descriptors,
  db_error__field_indices_by_name,
  1,  db_error__number_ranges,
  (ProtobufCMessageInit) db_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_query_result__field_descriptors[5] =
{
  {
    "fields",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbQueryResult, fields),
    &db_fields__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "affected_rows",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DbQueryResult, has_affected_rows),
    offsetof(DbQueryResult, affected_rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rows",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbQueryResult, rows),
    &db_rows__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DbQueryResult, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DbQueryResult, error),
    &db_error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_query_result__field_indices_by_name[] = {
  1,   /* field[1] = affected_rows */
  4,   /* field[4] = error */
  0,   /* field[0] = fields */
  2,   /* field[2] = rows */
  3,   /* field[3] = success */
};
static const ProtobufCIntRange db_query_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor db_query_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "db_query_result",
  "DbQueryResult",
  "DbQueryResult",
  "",
  sizeof(DbQueryResult),
  5,
  db_query_result__field_descriptors,
  db_query_result__field_indices_by_name,
  1,  db_query_result__number_ranges,
  (ProtobufCMessageInit) db_query_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
