/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: network_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "network_config.pb-c.h"
void   network_config__init
                     (NetworkConfig         *message)
{
  static NetworkConfig init_value = NETWORK_CONFIG__INIT;
  *message = init_value;
}
size_t network_config__get_packed_size
                     (const NetworkConfig *message)
{
  assert(message->base.descriptor == &network_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t network_config__pack
                     (const NetworkConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &network_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t network_config__pack_to_buffer
                     (const NetworkConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &network_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetworkConfig *
       network_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetworkConfig *)
     protobuf_c_message_unpack (&network_config__descriptor,
                                allocator, len, data);
}
void   network_config__free_unpacked
                     (NetworkConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &network_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor network_config__field_descriptors[5] =
{
  {
    "port",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number_of_conn",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, number_of_conn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keep_time",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, keep_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_enable_cache",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, is_enable_cache),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cache_count",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NetworkConfig, cache_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned network_config__field_indices_by_name[] = {
  4,   /* field[4] = cache_count */
  3,   /* field[3] = is_enable_cache */
  2,   /* field[2] = keep_time */
  1,   /* field[1] = number_of_conn */
  0,   /* field[0] = port */
};
static const ProtobufCIntRange network_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor network_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "network_config",
  "NetworkConfig",
  "NetworkConfig",
  "",
  sizeof(NetworkConfig),
  5,
  network_config__field_descriptors,
  network_config__field_indices_by_name,
  1,  network_config__number_ranges,
  (ProtobufCMessageInit) network_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
